// Generated from the hash-checked approved runtime. Do not edit, except that
// revision-id is spliced from common/reims_target.hpp (REIMS_REVISION_B64).
static const char selftest_profiles[] = R"REIMS(<array>
	<dict>
		<key>CFBundleIdentifier</key>
		<string>lab.reims.ReimsADLManualActivation</string>
		<key>IOClass</key>
		<string>ReimsADLManualMatchProbe</string>
		<key>IOMatchCategory</key>
		<string>ReimsADLManualMatchProbe</string>
		<key>IOPCIPrimaryMatch</key>
		<string>0xffff8086</string>
		<key>IOPropertyMatch</key>
		<dict>
			<key>device-id</key>
			<data>
			//8AAA==
			</data>
			<key>revision-id</key>
			<data>
			)REIMS" REIMS_REVISION_B64 R"REIMS(
			</data>
			<key>vendor-id</key>
			<data>
			hoAAAA==
			</data>
		</dict>
		<key>IOProviderClass</key>
		<string>IOPCIDevice</string>
		<key>ReimsManualSessionPersonality</key>
		<true/>
	</dict>
</array>)REIMS";
static const char runtime_profiles[] = R"REIMS(<array>
	<dict>
		<key>CFBundleIdentifier</key>
		<string>com.apple.driver.AppleIntelTGLGraphics</string>
		<key>Development</key>
		<dict>
			<key>AddressMode</key>
			<integer>64</integer>
			<key>AddressSpaceEnableMask</key>
			<integer>3</integer>
			<key>AllowIOSurfaceRenderCompression</key>
			<integer>0</integer>
			<key>CsbProcModeSelect</key>
			<integer>0</integer>
			<key>DisablePageFaultHandling</key>
			<integer>0</integer>
			<key>DisplaySurfaceInEDRAM</key>
			<integer>1</integer>
			<key>EUThrottle</key>
			<integer>0</integer>
			<key>EnableMultiContext</key>
			<integer>1</integer>
			<key>EnablePlaneRotation</key>
			<integer>0</integer>
			<key>EnablePreemption</key>
			<integer>1</integer>
			<key>ForceDisableEDRAM</key>
			<integer>0</integer>
			<key>GraphicsSchedulerSelect</key>
			<integer>5</integer>
			<key>MetalCoalesce</key>
			<integer>1</integer>
			<key>MultiForceWakeSelect</key>
			<integer>1</integer>
			<key>NewUtilizationAlgorithmEnable</key>
			<integer>1</integer>
			<key>PPGTT</key>
			<integer>1</integer>
			<key>PageTableMode</key>
			<integer>64</integer>
			<key>PanicOnGPUHang</key>
			<integer>0</integer>
			<key>PixelBackendThrottle</key>
			<integer>0</integer>
			<key>PreemptionDelayIntervalUS</key>
			<integer>160</integer>
			<key>PreemptionTimerIntervalUS</key>
			<integer>2000</integer>
			<key>RingSizeKB</key>
			<integer>32</integer>
			<key>SamplerDataFetchThrottle</key>
			<integer>0</integer>
			<key>SamplerPipeThrottle</key>
			<integer>0</integer>
			<key>SchedPmNotifyEnable</key>
			<integer>1</integer>
			<key>SchedThrottleCapMS</key>
			<integer>100</integer>
			<key>SchedulerFallbackOnFirmwareFail</key>
			<integer>1</integer>
			<key>SemaphoreWaitPoll</key>
			<integer>1</integer>
			<key>SeparateAddressSpace</key>
			<integer>1</integer>
			<key>SignalStampRange</key>
			<integer>1</integer>
			<key>SignalStampsPrimary</key>
			<integer>0</integer>
			<key>SingleChannelIndex</key>
			<integer>0</integer>
			<key>TelemetryDisable</key>
			<integer>0</integer>
			<key>WaitForComplete</key>
			<integer>0</integer>
		</dict>
		<key>GraphicsSchedulerSelect</key>
		<integer>5</integer>
		<key>IOClass</key>
		<string>IntelAccelerator</string>
		<key>IOMatchCategory</key>
		<string>IOAccelerator</string>
		<key>IOPCIPrimaryMatch</key>
		<string>0xffff8086</string>
		<key>IOProbeScore</key>
		<integer>1000</integer>
		<key>IOPropertyMatch</key>
		<dict>
			<key>device-id</key>
			<data>
			//8AAA==
			</data>
			<key>revision-id</key>
			<data>
			)REIMS" REIMS_REVISION_B64 R"REIMS(
			</data>
			<key>vendor-id</key>
			<data>
			hoAAAA==
			</data>
		</dict>
		<key>IOProviderClass</key>
		<string>IOPCIDevice</string>
		<key>MetalPluginClassName</key>
		<string>ReimsTahoeMetalDevice</string>
		<key>MetalPluginName</key>
		<string>ReimsTahoeTGLGraphicsMTLDriver</string>
		<key>ReimsADLOffscreenBringup</key>
		<true/>
		<key>ReimsManualPublicationDeferred</key>
		<true/>
		<key>ReimsManualSessionPersonality</key>
		<true/>
	</dict>
</array>)REIMS";
static const char link_profile[] = R"REIMS(<dict>
	<key>CFBundleIdentifier</key>
	<string>lab.reims.ReimsADLDesktopLink</string>
	<key>IOClass</key>
	<string>ReimsADLDesktopLink</string>
	<key>IOMatchCategory</key>
	<string>ReimsADLDesktopLink</string>
	<key>IOPropertyMatch</key>
	<dict>
		<key>ReimsADLOffscreenBringup</key>
		<true/>
	</dict>
	<key>IOProviderClass</key>
	<string>IntelAccelerator</string>
</dict>)REIMS";
